export const DYR = [
  { id: "isbjorn",    navn: "Isbjørn",    emoji: "🐻‍❄️", farge: "#eaf6ff", kant: "#7fc7e8",
    mysterium: "Hvem etterlot disse store potesporene i snøen?",
    brol: "Brrrooof!" },
  { id: "lowe",       navn: "Løve",       emoji: "🦁", farge: "#fff7e6", kant: "#f0c14b",
    mysterium: "Hvem sitt brøl runger over hele savannen?",
    brol: "RAAAOOOWR!" },
  { id: "elefant",    navn: "Elefant",    emoji: "🐘", farge: "#f1f6ec", kant: "#9bb87a",
    mysterium: "Hvem etterlot disse enorme rundesporene i jungelen?",
    brol: "Trööööt!" },
  { id: "gjok",       navn: "Gjøk",       emoji: "🐦", farge: "#f4f0fa", kant: "#b79fd6",
    mysterium: "Hvem la dette egget i et bol som ikke er sitt eget?",
    brol: "Ku-ku! Ku-ku!" },
  { id: "mus",        navn: "Mus",        emoji: "🐭", farge: "#fdf2f2", kant: "#e8a0a0",
    mysterium: "Hvem sin lille hale så vi forsvinne inn i hullet?",
    brol: "Pip pip!" },
  { id: "ugle",       navn: "Ugle",       emoji: "🦉", farge: "#f0f4ff", kant: "#8fa8d6",
    mysterium: "Hvem er det som ser deg selv midt på natten?",
    brol: "Huu-huu!" },
  { id: "pingvin",    navn: "Pingvin",    emoji: "🐧", farge: "#eef5ff", kant: "#6f8aa3",
    mysterium: "Hvem er det som ikke kan fly, men svømmer som en fisk?",
    brol: "Kvakk!" },
  { id: "rev",        navn: "Rev",        emoji: "🦊", farge: "#fff3e8", kant: "#e8a060",
    mysterium: "Hvem sine røde fotspor finner vi i snøen om morgenen?",
    brol: "Bjeff bjeff!" },
  { id: "sjiraff",    navn: "Sjiraff",    emoji: "🦒", farge: "#fdf6e3", kant: "#e0b35c",
    mysterium: "Hvem er det som alltid ser over trærne?",
    brol: "..." },
  { id: "krokodille", navn: "Krokodille", emoji: "🐊", farge: "#edfaf0", kant: "#5dbf7a",
    mysterium: "Hvem lurer stille i vannet og venter?",
    brol: "Sssss!" },
  { id: "hai",        navn: "Hai",        emoji: "🦈", farge: "#e8f4ff", kant: "#5b9fd4",
    mysterium: "Hvem sin finner ser vi stikke opp av vannet?",
    brol: "..." },
  { id: "gorilla",    navn: "Gorilla",    emoji: "🦍", farge: "#f2f2f2", kant: "#888888",
    mysterium: "Hvem dunker seg på brystet og er sterkest i jungelen?",
    brol: "Ugh ugh!" },
];
