export const DYR = [
  { slug: "hund",       navn: "Hund",       emoji: "🐕",  maxAlder: 15,  fakta: "Hunder sover nesten halvparten av dagen!" },
  { slug: "katt",       navn: "Katt",       emoji: "🐈",  maxAlder: 20,  fakta: "Katter kan pure i timevis!" },
  { slug: "hest",       navn: "Hest",       emoji: "🐎",  maxAlder: 30,  fakta: "Hester sover stående!" },
  { slug: "kamel",      navn: "Kamel",      emoji: "🐪",  maxAlder: 40,  fakta: "Kameler lagrer fett i pukkelene, ikke vann!" },
  { slug: "elefant",    navn: "Elefant",    emoji: "🐘",  maxAlder: 70,  fakta: "Elefanter husker steder de besøkte for mange år siden!" },
  { slug: "skilpadde",  navn: "Skilpadde",  emoji: "🐢",  maxAlder: 150, fakta: "Noen skilpadder er eldre enn oldeforeldrene dine!" },
  { slug: "papegoye",   navn: "Papegøye",   emoji: "🦜",  maxAlder: 80,  fakta: "Papegøyer kan lære hundrevis av ord!" },
  { slug: "gullfisk",   navn: "Gullfisk",   emoji: "🐟",  maxAlder: 10,  fakta: "Gullfisker husker faktisk mer enn 3 sekunder!" },
  { slug: "pingvin",    navn: "Pingvin",    emoji: "🐧",  maxAlder: 20,  fakta: "Pingviner er superflinke til å svømme men kan ikke fly!" },
  { slug: "love",       navn: "Løve",       emoji: "🦁",  maxAlder: 20,  fakta: "Løvinner jakter mest maten i flokken!" },
  { slug: "isbjorn",    navn: "Isbjørn",    emoji: "🐻‍❄️", maxAlder: 30,  fakta: "Isbjørner kan lukte mat på 30 kilometers avstand!" },
  { slug: "gorilla",    navn: "Gorilla",    emoji: "🦍",  maxAlder: 50,  fakta: "Gorillaer lager nye senger av blader hver natt!" },
  { slug: "delfin",     navn: "Delfin",     emoji: "🐬",  maxAlder: 50,  fakta: "Delfiner sover med ett øye åpent!" },
  { slug: "sjiraff",    navn: "Sjiraff",    emoji: "🦒",  maxAlder: 25,  fakta: "Sjiraffer sover bare 30 minutter om dagen!" },
  { slug: "krokodille", navn: "Krokodille", emoji: "🐊",  maxAlder: 70,  fakta: "Krokodiller har nesten ikke forandret seg på 200 millioner år!" },
  { slug: "orn",        navn: "Ørn",        emoji: "🦅",  maxAlder: 30,  fakta: "Ørner kan se fisk langt nede i vannet fra høyt oppe i lufta!" },
  { slug: "kanin",      navn: "Kanin",      emoji: "🐰",  maxAlder: 12,  fakta: "Kaniner tygger over 100 ganger i minuttet!" },
  { slug: "hamster",    navn: "Hamster",    emoji: "🐹",  maxAlder: 3,   fakta: "Hamstere kan ha mat i kinnene til de kommer hjem!" },
  { slug: "ku",         navn: "Ku",         emoji: "🐄",  maxAlder: 20,  fakta: "Kuer har beste venner og blir lei seg når de skilles!" },
  { slug: "gris",       navn: "Gris",       emoji: "🐷",  maxAlder: 15,  fakta: "Griser er like smarte som hunder!" },
  { slug: "ugle",       navn: "Ugle",       emoji: "🦉",  maxAlder: 25,  fakta: "Ugler kan fly nesten helt lydløst!" },
  { slug: "rev",        navn: "Rev",        emoji: "🦊",  maxAlder: 14,  fakta: "Rever bruker halen som teppe når det er kaldt!" },
  { slug: "bjorn",      navn: "Bjørn",      emoji: "🐻",  maxAlder: 30,  fakta: "Bjørner kan lukte mat veldig langt unna!" },
  { slug: "koala",      navn: "Koala",      emoji: "🐨",  maxAlder: 18,  fakta: "Koalaer sover ofte opptil 20 timer i døgnet!" },
  { slug: "hval",       navn: "Hval",       emoji: "🐋",  maxAlder: 90,  fakta: "Noen hvaler synger lange sanger under vann!" },
  { slug: "blekksprut", navn: "Blekksprut", emoji: "🐙",  maxAlder: 5,   fakta: "Blekkspruter har tre hjerter!" },
  { slug: "sommerfugl", navn: "Sommerfugl", emoji: "🦋",  maxAlder: 1,   fakta: "Sommerfugler smaker med føttene!" },
  { slug: "hai",        navn: "Hai",        emoji: "🦈",  maxAlder: 70,  fakta: "Haier har eksistert lenger enn dinosaurene!" },
  { slug: "sebra",      navn: "Sebra",      emoji: "🦓",  maxAlder: 25,  fakta: "Ingen sebraer har helt like striper!" },
  { slug: "neshorn",    navn: "Neshorn",    emoji: "🦏",  maxAlder: 50,  fakta: "Neshorn har horn som er laget av det samme stoffet som negler!" },
  { slug: "flodhest",   navn: "Flodhest",   emoji: "🦛",  maxAlder: 50,  fakta: "Flodhester kan løpe overraskende fort på land!" },
];
