export const DYR = [
  { id: "isbjorn",    navn: "Isbjørn",    emoji: "🐻‍❄️", farge: "#eaf6ff", kant: "#7fc7e8",
    fakta: ["Isbjørnen er det største landrovdyret i hele verden!", "Den svømmer så bra at noen kaller den et sjøpattedyr.", "Den kan lukte en sel over 30 kilometer unna."] },
  { id: "lowe",       navn: "Løve",       emoji: "🦁", farge: "#fff7e6", kant: "#f0c14b",
    fakta: ["Løven kalles ofte dyrenes konge.", "Bare hannløver har manke — den store pelskragen.", "Et brøl kan høres åtte kilometer unna!"] },
  { id: "elefant",    navn: "Elefant",    emoji: "🐘", farge: "#f1f6ec", kant: "#9bb87a",
    fakta: ["Elefanten er det største dyret som lever på land.", "Den bruker snabelen til å drikke, spise og klemme!", "Elefantbabyer suger på snabelen for å trøste seg."] },
  { id: "pingvin",    navn: "Pingvin",    emoji: "🐧", farge: "#eef5ff", kant: "#6f8aa3",
    fakta: ["Pingviner kan ikke fly, men er mestere i svømming.", "Pappaen holder egget varmt mellom beina hele vinteren.", "Noen pingviner lever der det er så kaldt som minus 60 grader!"] },
  { id: "sjiraff",    navn: "Sjiraff",    emoji: "🦒", farge: "#fdf6e3", kant: "#e0b35c",
    fakta: ["Sjiraffen er det høyeste dyret i verden.", "Den sover bare 30 minutter om dagen — i korte lunder.", "Tungen er så lang at den kan rense ørene sine med den!"] },
  { id: "delfin",     navn: "Delfin",     emoji: "🐬", farge: "#e8f9ff", kant: "#5bc4e8",
    fakta: ["Delfiner sover med ett øye åpent!", "De bruker klikkende lyder for å snakke med hverandre.", "En delfin kan svømme opptil 55 km i timen."] },
  { id: "ugle",       navn: "Ugle",       emoji: "🦉", farge: "#f0f4ff", kant: "#8fa8d6",
    fakta: ["Ugler kan fly nesten helt lydløst.", "Hodet kan snu seg nesten helt rundt — 270 grader!", "Ugler ser ikke farge, men ser perfekt i mørket."] },
  { id: "hai",        navn: "Hai",        emoji: "🦈", farge: "#e8f4ff", kant: "#5b9fd4",
    fakta: ["Haier har eksistert lenger enn dinosaurene!", "De mister og får nye tenner hele livet.", "De fleste haier er ikke farlige for mennesker."] },
  { id: "gorilla",    navn: "Gorilla",    emoji: "🦍", farge: "#f2f2f2", kant: "#888888",
    fakta: ["Gorillaer lager nye senger av blader hver eneste natt.", "De er veldig kloke og kan lære tegn-språk.", "Gorillaer er nesten 98% like mennesker i genene sine."] },
  { id: "krokodille", navn: "Krokodille", emoji: "🐊", farge: "#edfaf0", kant: "#5dbf7a",
    fakta: ["Krokodiller har nesten ikke forandret seg på 200 millioner år!", "De er overraskende gode løpere på land.", "Mammaen bærer ungene forsiktig i munnen ned til vannet."] },
  { id: "blekksprut", navn: "Blekksprut", emoji: "🐙", farge: "#f8eeff", kant: "#c09fd6",
    fakta: ["Blekkspruter har tre hjerter!", "De kan skifte farge på bare et halvt sekund.", "Hvert av de åtte armene har sin egen lille hjerne."] },
  { id: "hval",       navn: "Hval",       emoji: "🐋", farge: "#e8f0ff", kant: "#6080c4",
    fakta: ["Noen hvaler synger sanger som kan høres hundrevis av kilometer unna.", "Blåhvalen er det største dyret som noensinne har levd på jorda.", "Hvaler puster gjennom et hull på toppen av hodet."] },
  { id: "rev",        navn: "Rev",        emoji: "🦊", farge: "#fff3e8", kant: "#e8a060",
    fakta: ["Rever bruker halen som teppe når det er kaldt.", "De hører mus som løper under snøen og hopper rett ned på dem.", "En rev kan gjøre over 40 forskjellige lyder!"] },
  { id: "koala",      navn: "Koala",      emoji: "🐨", farge: "#f5f0ea", kant: "#b0987a",
    fakta: ["Koalaer sover opptil 20 timer i døgnet.", "De spiser nesten bare eukalyptusblader — som er giftige for de fleste dyr.", "Babyen bor i mammaens pung i seks måneder."] },
  { id: "sommerfugl", navn: "Sommerfugl", emoji: "🦋", farge: "#fff0f8", kant: "#e080c0",
    fakta: ["Sommerfugler smaker med føttene!", "De startet livet som en kjedelig kålorm.", "Vingene er dekket av bittesmå skjell som lager fargene."] },
];
