// bilder: legg PNG-filer fra Flaticon i /public/dino/
// Filnavn må matche img-feltet her.
// Inntil bildene er klare brukes emoji som fallback.

export const DINO = [
  {
    id: "trex",
    navn: "T-Rex",
    emoji: "🦖",
    img: "/dino/trex.png",
    bæsj: "💩",           // lang og tynn pølse
    bæsjBeskrivelse: "lang og tynn, som en pølse — kjøtt til frokost, lunsj og middag!",
    fakta: "T-Rex hadde armer så korte at de ikke nådde munnen sin.",
    fakta2: "Et bitt fra T-Rex var sterkere enn tre biler stilt oppå hverandre!",
    farge: "#fff0e8", kant: "#e8804a",
  },
  {
    id: "triceratops",
    navn: "Triceratops",
    emoji: "🦕",
    img: "/dino/triceratops.png",
    bæsj: "🟤🟤🟤",
    bæsjBeskrivelse: "store runde kuler — planter lager mye avfall!",
    fakta: "Triceratops hadde tre horn og et skjold bak hodet for å beskytte seg.",
    fakta2: "Den spiste bare planter, men var ikke noe å tulle med!",
    farge: "#f0f8ec", kant: "#6eb85a",
  },
  {
    id: "stegosaurus",
    navn: "Stegosaurus",
    emoji: "🦕",
    img: "/dino/stegosaurus.png",
    bæsj: "🟤🟤🟤🟤",
    bæsjBeskrivelse: "store og klumpete hauger — masse gress inn, masse bæsj ut!",
    fakta: "Stegosaurus hadde plater langs ryggen som kanskje regulerte kroppstemperaturen.",
    fakta2: "Hjernen var på størrelse med en valnøtt, men magen var kjempestor!",
    farge: "#f0f4ff", kant: "#8090d0",
  },
  {
    id: "velociraptor",
    navn: "Velociraptor",
    emoji: "🦖",
    img: "/dino/velociraptor.png",
    bæsj: "💩💩",
    bæsjBeskrivelse: "to tynne pølser — rask inn, rask ut!",
    fakta: "Velociraptor hadde faktisk fjær, omtrent som en stor fugl.",
    fakta2: "Den var bare på størrelse med en kalkun, ikke som i Jurassic Park!",
    farge: "#fdf6e3", kant: "#c8a850",
  },
  {
    id: "brachiosaurus",
    navn: "Brachiosaurus",
    emoji: "🦕",
    img: "/dino/brachiosaurus.png",
    bæsj: "🟤🟤🟤🟤🟤",
    bæsjBeskrivelse: "en hel haug — når du spiser hundrevis av kilo med blader hver dag...",
    fakta: "Brachiosaurus var nesten 26 meter lang og spiste bare fra trærnes topper.",
    fakta2: "Den veide like mye som 10 elefanter!",
    farge: "#e8f4ff", kant: "#5090c0",
  },
  {
    id: "pterodaktyl",
    navn: "Pterodaktyl",
    emoji: "🦅",
    img: "/dino/pterodaktyl.png",
    bæsj: "💦💩",
    bæsjBeskrivelse: "litt flytende og litt fast — akkurat som fugler gjør det!",
    fakta: "Pterodaktyl var egentlig ikke en dinosaur, men en flyveøgle.",
    fakta2: "Den kunne ha et vingespenn på over ni meter!",
    farge: "#faf0ff", kant: "#a070c0",
  },
  {
    id: "ankylosaurus",
    navn: "Ankylosaurus",
    emoji: "🦕",
    img: "/dino/ankylosaurus.png",
    bæsj: "🟤🟤🟤",
    bæsjBeskrivelse: "tykke klumper — panseret betyr trygg bæsj i fred!",
    fakta: "Ankylosaurus var dekt av beinplater som en levende tanks.",
    fakta2: "Halen hadde en tung kjølle den kunne slå med som en hammer!",
    farge: "#f0ffe8", kant: "#70a850",
  },
  {
    id: "spinosaurus",
    navn: "Spinosaurus",
    emoji: "🦖",
    img: "/dino/spinosaurus.png",
    bæsj: "💩💩💩",
    bæsjBeskrivelse: "lang og bred — den spiste mest fisk, og fisk lager mye bæsj!",
    fakta: "Spinosaurus var sannsynligvis større enn T-Rex og spiste mest fisk.",
    fakta2: "Den hadde en stor segl på ryggen som kanskje ble brukt til å imponere.",
    farge: "#e8fff8", kant: "#40b890",
  },
];
