// bilder: legg PNG-filer fra Flaticon i /public/dino/
// Filnavn må matche img-feltet her.

export const DINO = [
  {
    id: "trex",
    navn: "T-Rex",
    emoji: "🦖",
    img: "/dino/trex.png",
    bæsj: "🌭",
    bæsjBeskrivelse: "én lang tynn pølse — kjøtt til frokost, lunsj og middag!",
    fakta: "T-Rex hadde armer så korte at de ikke nådde munnen sin.",
    fakta2: "Et bitt fra T-Rex var sterkere enn tre biler stilt oppå hverandre!",
    farge: "#fff0e8", kant: "#e8804a",
  },
  {
    id: "triceratops",
    navn: "Triceratops",
    emoji: "🦕",
    img: "/dino/triceratops.png",
    bæsj: "🫚🍵🌿",
    bæsjBeskrivelse: "grønn og grøtete — bare planter inn betyr grønn suppe ut!",
    fakta: "Triceratops hadde tre horn og et skjold bak hodet for å beskytte seg.",
    fakta2: "Den spiste bare planter, men var ikke noe å tulle med!",
    farge: "#f0f8ec", kant: "#6eb85a",
  },
  {
    id: "stegosaurus",
    navn: "Stegosaurus",
    emoji: "🦕",
    img: "/dino/stegosaurus.png",
    bæsj: "🥜🥜🥜🥜🥜",
    bæsjBeskrivelse: "fem store runde kuler — masse gress inn, masse kuler ut!",
    fakta: "Stegosaurus hadde plater langs ryggen som kanskje regulerte kroppstemperaturen.",
    fakta2: "Hjernen var på størrelse med en valnøtt, men magen var kjempestor!",
    farge: "#f0f4ff", kant: "#8090d0",
  },
  {
    id: "velociraptor",
    navn: "Velociraptor",
    emoji: "🦖",
    img: "/dino/velociraptor.png",
    bæsj: "🌭🌭",
    bæsjBeskrivelse: "to små pølser — liten kropp, liten bæsj, men like stinkende!",
    fakta: "Velociraptor hadde faktisk fjær, omtrent som en stor fugl.",
    fakta2: "Den var bare på størrelse med en kalkun, ikke som i Jurassic Park!",
    farge: "#fdf6e3", kant: "#c8a850",
  },
  {
    id: "diplodocus",
    navn: "Diplodocus",
    emoji: "🦕",
    img: "/dino/diplodocus.png",
    bæsj: "🪣🪣🪣🪣",
    bæsjBeskrivelse: "fire bøtter fulle — med den lengste halen i verden trenger du mye drivstoff!",
    fakta: "Diplodocus hadde den lengste halen av alle dinosaurer — nesten som et tau!",
    fakta2: "Den brukte halen som en svær pisk som kunne lage smell høyere enn et tordenskrall!",
    farge: "#e8f4ff", kant: "#5090c0",
  },
  {
    id: "pterodaktyl",
    navn: "Pterodaktyl",
    emoji: "🦅",
    img: "/dino/pterodaktyl.png",
    bæsj: "🎨",
    bæsjBeskrivelse: "flytende og hvit som maling — akkurat som fugler skvetter fra oven!",
    fakta: "Pterodaktyl var egentlig ikke en dinosaur, men en flyveøgle.",
    fakta2: "Den kunne ha et vingespenn på over ni meter — større enn en bil er lang!",
    farge: "#faf0ff", kant: "#a070c0",
  },
  {
    id: "ankylosaurus",
    navn: "Ankylosaurus",
    emoji: "🦕",
    img: "/dino/ankylosaurus.png",
    bæsj: "🪨🪨🪨",
    bæsjBeskrivelse: "tre tunge steiner — panseret betyr ro til å bæsje i fred!",
    fakta: "Ankylosaurus var dekket av beinplater som en levende tanks.",
    fakta2: "Halen hadde en tung kjølle den kunne slå med som en sleggehammer!",
    farge: "#f0ffe8", kant: "#70a850",
  },
  {
    id: "spinosaurus",
    navn: "Spinosaurus",
    emoji: "🦖",
    img: "/dino/spinosaurus.png",
    bæsj: "🐟🐟🐟",
    bæsjBeskrivelse: "tre fiskeskjeletter — den spiste nesten bare fisk, så det lukter deretter!",
    fakta: "Spinosaurus var sannsynligvis større enn T-Rex og spiste mest fisk.",
    fakta2: "Den hadde en stor segl på ryggen som kanskje ble brukt til å imponere.",
    farge: "#e8fff8", kant: "#40b890",
  },
];
